### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by currymz** [TomorrowDAOProject/tomorrowDAO-interface#539]
### Expected Behavior
tg bot task list

### Specifications
As a `user`, I would like to participate in more activities to earn points.

**Features:**

**Development Tasks:**
- [ ] Render the task list
- [ ] Report of completed tasks
- [ ] Front-end determines whether the task is completed.

### Dependencies
server

### References
null
